### ISSUE TITLE
No clear instructions..

### ISSUE THREAD

**Issue by XoxRumbleLorexoX** [dliedke/FixNugetCache#2]
How do you use this to solve this issue - 
Unable to retrieve package from http://www.nuget.org/api/v2/Packages(Id='System.Memory',Version='4.5.4')
System.Xml.XmlException: '', hexadecimal value 0x1F, is an invalid character. Line 1, position 1.

**Comment by dliedke** [comment]
Strange, this XML is retrieved from the internet. I tested here and it looks OK. 
![Screenshot_20220511-081613](https://user-images.githubusercontent.com/16479450/167836968-cf7b77e7-28ca-4c3c-a132-e8be7f131fde.jpg)
Maybe you are using some proxy or VPN? 

Thanks!
